### PR TITLE
UofT-DSI | Python - Assignment 1 -updatev3

### PR DESCRIPTION
**Pull request by CatherineZYH**
## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by CatherineZYH** [comment]
@juliagallucci

**Review by juliagallucci — CHANGES_REQUESTED** [review]
Code does not execute without error. Please come to office hours for assistance.

**Comment by CatherineZYH** [comment]
@juliagallucci

**Comment by CatherineZYH** [comment]
finished my updates.

**Review by juliagallucci — CHANGES_REQUESTED** [review]
Part B is incorrect; here you need to modify code from part A so that it takes into account case sensitivity, when that new argument is True
Please revise

**Comment by CatherineZYH** [comment]
@juliagallucci

**Review by juliagallucci — CHANGES_REQUESTED** [review]
Part B executes with error, please come to office hours for further assistance

**Comment by CatherineZYH** [comment]
Hey @juliagallucci , I can run it and without error,  I am using windows system, is that affected?
https://github.com/CatherineZYH/python/assets/102681357/7cc2bf5c-c2f7-4379-929a-898a258fa08c

**Review by juliagallucci — APPROVED** [review]
Great! Your code executes well without error. Some suggestions for improvement would be to remove redundant lines (ie conditional statements already return a boolean true/false, so no need to code this)

**Pull request closed without merging**
